<?php

/**
 * This is the model base class for the table "Radio_show".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RadioShow".
 *
 * Columns in table "Radio_show" available as properties of the model,
 * followed by relations of table "Radio_show" available as properties of the model.
 *
 * @property integer $id
 * @property string $radio_show_name
 * @property string $Description
 *
 * @property Bookings[] $bookings
 */
abstract class BaseRadioShow extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'Radio_show';
    }

    public static function representingColumn() {
        return 'radio_show_name';
    }

    public function rules() {
        return array(
            array('radio_show_name, Description', 'required'),
            array('radio_show_name', 'length', 'max'=>255),
            array('Description', 'length', 'max'=>500),
            array('id, radio_show_name, Description', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'bookings' => array(self::HAS_MANY, 'Bookings', 'radio_show_name'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'radio_show_name' => Yii::t('app', 'Radio Show Name'),
                'Description' => Yii::t('app', 'Description'),
                'bookings' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('radio_show_name', $this->radio_show_name, true);
        $criteria->compare('Description', $this->Description, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}