<?php

/**
 * This is the model base class for the table "Time_belt".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TimeBelt".
 *
 * Columns in table "Time_belt" available as properties of the model,
 * followed by relations of table "Time_belt" available as properties of the model.
 *
 * @property integer $id
 * @property string $time_belt_title
 * @property double $amount
 * @property string $description
 *
 * @property Bookings[] $bookings
 */
abstract class BaseTimeBelt extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'Time_belt';
    }

    public static function representingColumn() {
        return 'time_belt_title';
    }

    public function rules() {
        return array(
            array('time_belt_title, amount, description', 'required'),
            array('amount', 'numerical'),
            array('time_belt_title', 'length', 'max'=>255),
            array('description', 'length', 'max'=>500),
            array('id, time_belt_title, amount, description', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'bookings' => array(self::HAS_MANY, 'Bookings', 'time_belt'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'time_belt_title' => Yii::t('app', 'Time Belt Title'),
                'amount' => Yii::t('app', 'Amount'),
                'description' => Yii::t('app', 'Description'),
                'bookings' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('time_belt_title', $this->time_belt_title, true);
        $criteria->compare('amount', $this->amount);
        $criteria->compare('description', $this->description, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}